site_name: fastlane docs
theme: readthedocs
site_author: "fastlane team"
site_description: "Documentation for fastlane tools, the easiest way to automate building and releasing your iOS and Android apps"
strict: true
